### ISSUE TITLE
api/v1/trips/tripById dose not work

### ISSUE THREAD

**Issue by cseh17** [sebastianknopf/gtfs-rest-api#1]
The endpoint mentioned above, delivers an error even when calling it with a valid (double checked) trip id. The problem seems to be in the BaseController.

Calling the endpoint without a trip id, seems to deliver a custom error message created in the TripController.

**Comment by sebastianknopf** [comment]
Hi there & sorry for my delayed answer. Can you post the complete error message or the stack trace?
